import streamlit as st
import random

missions = [
    "Alabama Birmingham Mission",
    "Alaska Anchorage Mission",
    "Albania Tirana Mission",
    "Angola Luanda Mission",
    "Argentina Bahia Blanca Mission",
    "Argentina Buenos Aires North Mission",
    "Argentina Buenos Aires South Mission",
    "Argentina Cordoba Mission",
    "Argentina Mendoza Mission",
    "Argentina Neuquen Mission",
    "Argentina Resistencia Mission",
    "Argentina Rosario Mission",
    "Argentina Salta Mission",
    "Argentina Santa Fe Mission",
    "Argentina Tucuman Mission",
    "Arizona Gilbert Mission",
    "Arizona Mesa Mission",
    "Arizona Phoenix Mission",
    "Arizona Scottsdale Mission",
    "Arizona Tempe Mission",
    "Arizona Tucson Mission",
    "Arizona Yuma Mission",
    "Armenia/Georgia Mission",
    "Australia Adelaide Mission",
    "Australia Brisbane Mission",
    "Australia Melbourne Mission",
    "Australia Perth Mission",
    "Australia Sydney Mission",
    "Australia Sydney North Mission",
    "Austria Vienna Mission",
    "Bahamas Nassau Mission",
    "Bangladesh Dhaka Mission",
    "Barbados Bridgetown Mission",
    "Belgium/Netherlands Mission",
    "Benin Cotonou Mission",
    "Bolivia Cochabamba Mission",
    "Bolivia La Paz Mission",
    "Bolivia Santa Cruz Mission",
    "Bolivia Santa Cruz North Mission",
    "Bolivia Tarija Mission",
    "Bosnia and Herzegovina Sarajevo Mission",
    "Botswana/Namibia Mission",
    "Brazil Belem Mission",
    "Brazil Belo Horizonte Mission",
    "Brazil Brasilia Mission",
    "Brazil Campinas Mission",
    "Brazil Curitiba Mission",
    "Brazil Curitiba South Mission",
    "Brazil Florianopolis Mission",
    "Brazil Fortaleza Mission",
    "Brazil Fortaleza East Mission",
    "Brazil Goiania Mission",
    "Brazil Joao Pessoa Mission",
    "Brazil Londrina Mission",
    "Brazil Maceio Mission",
    "Brazil Manaus Mission",
    "Brazil Natal Mission",
    "Brazil Piracicaba Mission",
    "Brazil Porto Alegre Mission",
    "Brazil Porto Alegre North Mission",
    "Brazil Recife Mission",
    "Brazil Recife North Mission",
    "Brazil Ribeirao Preto Mission",
    "Brazil Rio de Janeiro Mission",
    "Brazil Rio de Janeiro North Mission",
    "Brazil Salvador Mission",
    "Brazil Santa Maria Mission",
    "Brazil Santos Mission",
    "Brazil Sao Paulo East Mission",
    "Brazil Sao Paulo Interlagos Mission",
    "Brazil Sao Paulo North Mission",
    "Brazil Sao Paulo South Mission",
    "Brazil Sao Paulo West Mission",
    "Brazil Teresina Mission",
    "Brazil Vitoria Mission",
    "Bulgaria Sofia Mission",
    "California Anaheim Mission",
    "California Arcadia Mission",
    "California Bakersfield Mission",
    "California Carlsbad Mission",
    "California Fresno Mission",
    "California Irvine Mission",
    "California Long Beach Mission",
    "California Los Angeles Mission",
    "California Modesto Mission",
    "California Oakland/San Francisco Mission",
    "California Rancho Cucamonga Mission",
    "California Redlands Mission",
    "California Riverside Mission",
    "California Sacramento Mission",
    "California San Bernardino Mission",
    "California San Diego Mission",
    "California San Fernando Mission",
    "California San Francisco Mission",
    "California San Jose Mission",
    "California Santa Rosa Mission",
    "California Ventura Mission",
    "Cambodia Phnom Penh Mission",
    "Cameroon Yaounde Mission",
    "Canada Calgary Mission",
    "Canada Edmonton Mission",
    "Canada Halifax Mission",
    "Canada Montreal Mission",
    "Canada Toronto Mission",
    "Canada Vancouver Mission",
    "Canada Winnipeg Mission",
    "Cape Verde Praia Mission",
    "Caribbean Area Mission",
    "Central Eurasian Mission",
    "Chad N'Djamena Mission",
    "Chile Antofagasta Mission",
    "Chile Concepcion Mission",
    "Chile Concepcion South Mission",
    "Chile Osorno Mission",
    "Chile Rancagua Mission",
    "Chile Santiago East Mission",
    "Chile Santiago North Mission",
    "Chile Santiago South Mission",
    "Chile Santiago West Mission",
    "Chile Vina del Mar Mission",
    "China Hong Kong Mission",
    "Colombia Barranquilla Mission",
    "Colombia Bogota North Mission",
    "Colombia Bogota South Mission",
    "Colombia Cali Mission",
    "Colombia Medellin Mission",
    "Colombia Villavicencio Mission",
    "Congo Brazzaville Mission",
    "Congo Kinshasa Mission",
    "Costa Rica San Jose Mission",
    "Cote d'Ivoire Abidjan East Mission",
    "Cote d'Ivoire Abidjan North Mission",
    "Cote d'Ivoire Abidjan West Mission",
    "Cote d'Ivoire Yamoussoukro Mission",
    "Croatia Zagreb Mission",
    "Czech/Slovak Mission",
    "Denmark Copenhagen Mission",
    "Dominican Republic Santiago Mission",
    "Dominican Republic Santo Domingo East Mission",
    "Dominican Republic Santo Domingo West Mission",
    "DR Congo Kananga Mission",
    "DR Congo Kinshasa East Mission",
    "DR Congo Kinshasa West Mission",
    "DR Congo Lubumbashi Mission",
    "DR Congo Mbuji-Mayi Mission",
    "Ecuador Guayaquil North Mission",
    "Ecuador Guayaquil South Mission",
    "Ecuador Quito Mission",
    "Ecuador Quito North Mission",
    "El Salvador San Salvador East Mission",
    "El Salvador San Salvador West/Belize Mission",
    "England Birmingham Mission",
    "England Bristol Mission",
    "England Leeds Mission",
    "England London Mission",
    "England London South Mission",
    "England Manchester Mission",
    "England Newcastle Mission",
    "England Scotland/Ireland Mission",
    "Estonia Tallinn Mission",
    "Eswatini Mbabane Mission",
    "Ethiopia Addis Ababa Mission",
    "Fiji Suva Mission",
    "Finland Helsinki Mission",
    "Florida Fort Lauderdale Mission",
    "Florida Jacksonville Mission",
    "Florida Orlando Mission",
    "Florida Tampa Mission",
    "France Lyon Mission",
    "France Paris Mission",
    "French Polynesia Papeete Mission",
    "Gabon Libreville Mission",
    "Georgia Atlanta Mission",
    "Georgia Tbilisi Mission",
    "Germany Berlin Mission",
    "Germany Frankfurt Mission",
    "Germany Munich/Austria Mission",
    "Ghana Accra Mission",
    "Ghana Accra West Mission",
    "Ghana Cape Coast Mission",
    "Ghana Kumasi Mission",
    "Ghana Takoradi Mission",
    "Greece Athens Mission",
    "Guatemala Coban Mission",
    "Guatemala Guatemala City Central Mission",
    "Guatemala Guatemala City East Mission",
    "Guatemala Guatemala City North Mission",
    "Guatemala Guatemala City South Mission",
    "Guatemala Quetzaltenango Mission",
    "Guatemala Retalhuleu Mission",
    "Guatemala San Marcos Mission",
    "Guinea Conakry Mission",
    "Guyana Georgetown Mission",
    "Haiti Port-au-Prince Mission",
    "Honduras Comayaguela Mission",
    "Honduras San Pedro Sula East Mission",
    "Honduras San Pedro Sula West Mission",
    "Honduras Tegucigalpa Mission",
    "Hong Kong China Mission",
    "Hungary Budapest Mission",
    "Iceland Reykjavik Mission",
    "India Bengaluru Mission",
    "India Hyderabad Mission",
    "India New Delhi Mission",
    "Indonesia Jakarta Mission",
    "Ireland Dublin Mission",
    "Italy Milan Mission",
    "Italy Rome Mission",
    "Jamaica Kingston Mission",
    "Japan Fukuoka Mission",
    "Japan Kobe Mission",
    "Japan Nagoya Mission",
    "Japan Sapporo Mission",
    "Japan Sendai Mission",
    "Japan Tokyo Mission",
    "Japan Tokyo South Mission",
    "Jordan Amman Mission",
    "Kansas Wichita Mission",
    "Kenya Nairobi Mission",
    "Kiribati Tarawa Mission",
    "Kosovo Pristina Mission",
    "Kyrgyzstan Bishkek Mission",
    "Laos Vientiane Mission",
    "Latvia Riga Mission",
    "Lebanon Beirut Mission",
    "Lesotho Maseru Mission",
    "Liberia Monrovia Mission",
    "Lithuania Vilnius Mission",
    "Madagascar Antananarivo Mission",
    "Malawi Lilongwe Mission",
    "Malaysia Kuala Lumpur Mission",
    "Malta Valletta Mission",
    "Marshall Islands Majuro Mission",
    "Mauritius Port Louis Mission",
    "Mexico Aguascalientes Mission",
    "Mexico Cancun Mission",
    "Mexico Culiacan Mission",
    "Mexico Guadalajara East Mission",
    "Mexico Guadalajara Mission",
    "Mexico Hermosillo Mission",
    "Mexico Merida Mission",
    "Mexico Mexico City Chalco Mission",
    "Mexico Mexico City East Mission",
    "Mexico Mexico City North Mission",
    "Mexico Mexico City Northwest Mission",
    "Mexico Mexico City South Mission",
    "Mexico Mexico City Southeast Mission",
    "Mexico Mexico City West Mission",
    "Mexico Monterrey East Mission",
    "Mexico Monterrey West Mission",
    "Mexico Oaxaca Mission",
    "Mexico Pachuca Mission",
    "Mexico Puebla North Mission",
    "Mexico Puebla South Mission",
    "Mexico Queretaro Mission",
    "Mexico Reynosa Mission",
    "Mexico Saltillo Mission",
    "Mexico San Luis Potosi Mission",
    "Mexico Tampico Mission",
    "Mexico Tijuana Mission",
    "Mexico Torreon Mission",
    "Mexico Tuxtla Gutierrez Mission",
    "Mexico Veracruz Mission",
    "Mexico Villahermosa Mission",
    "Micronesia Guam Mission",
    "Moldova Chisinau Mission",
    "Mongolia Ulaanbaatar Mission",
    "Montenegro Podgorica Mission",
    "Morocco Rabat Mission",
    "Mozambique Maputo Mission",
    "Namibia Windhoek Mission",
    "Nepal Kathmandu Mission",
    "Netherlands Amsterdam Mission",
    "New Zealand Auckland Mission",
    "New Zealand Hamilton Mission",
    "New Zealand Wellington Mission",
    "Nicaragua Managua Mission",
    "Niger Niamey Mission",
    "Nigeria Abuja Mission",
    "Nigeria Benin City Mission",
    "Nigeria Calabar Mission",
    "Nigeria Enugu Mission",
    "Nigeria Ibadan Mission",
    "Nigeria Ilorin Mission",
    "Nigeria Jos Mission",
    "Nigeria Lagos East Mission",
    "Nigeria Lagos Mission",
    "Nigeria Lagos West Mission",
    "Nigeria Owerri Mission",
    "Nigeria Port Harcourt Mission",
    "Nigeria Uyo Mission",
    "North Macedonia Skopje Mission",
    "Norway Oslo Mission",
    "Pacific Area Mission",
    "Pakistan Islamabad Mission",
    "Panama Panama City Mission",
    "Papua New Guinea Lae Mission",
    "Papua New Guinea Port Moresby Mission",
    "Paraguay Asuncion Mission",
    "Paraguay Ciudad del Este Mission",
    "Peru Arequipa Mission",
    "Peru Chiclayo Mission",
    "Peru Cusco Mission",
    "Peru Huancayo Mission",
    "Peru Iquitos Mission",
    "Peru Lima Central Mission",
    "Peru Lima East Mission",
    "Peru Lima North Mission",
    "Peru Lima South Mission",
    "Peru Lima West Mission",
    "Peru Piura Mission",
    "Peru Trujillo North Mission",
    "Peru Trujillo South Mission",
    "Philippines Angeles Mission",
    "Philippines Antipolo Mission",
    "Philippines Bacolod Mission",
    "Philippines Baguio Mission",
    "Philippines Butuan Mission",
    "Philippines Cabanatuan Mission",
    "Philippines Cagayan de Oro Mission",
    "Philippines Cebu Mission",
    "Philippines Cebu East Mission",
    "Philippines Davao Mission",
    "Philippines General Santos Mission",
    "Philippines Iloilo Mission",
    "Philippines Laoag Mission",
    "Philippines Legazpi Mission",
    "Philippines Manila Mission",
    "Philippines Manila East Mission",
    "Philippines Naga Mission",
    "Philippines Olongapo Mission",
    "Philippines Quezon City Mission",
    "Philippines Quezon City North Mission",
    "Philippines San Pablo Mission",
    "Philippines Tacloban Mission",
    "Philippines Urdaneta Mission",
    "Philippines Zamboanga Mission",
    "Poland Warsaw Mission",
    "Portugal Lisbon Mission",
    "Puerto Rico San Juan Mission",
    "Republic of Congo Brazzaville Mission",
    "Romania Bucharest Mission",
    "Russia Moscow Mission",
    "Russia Novosibirsk Mission",
    "Russia Rostov-na-Donu Mission",
    "Russia St. Petersburg Mission",
    "Russia Vladivostok Mission",
    "Rwanda Kigali Mission",
    "Samoa Apia Mission",
    "Samoa Pago Pago Mission",
    "Scotland/Ireland Mission",
    "Senegal Dakar Mission",
    "Serbia Belgrade Mission",
    "Sierra Leone Bo Mission",
    "Sierra Leone Freetown Mission",
    "Singapore Mission",
    "Slovakia Bratislava Mission",
    "Slovenia Ljubljana Mission",
    "Solomon Islands Honiara Mission",
    "South Africa Cape Town Mission",
    "South Africa Durban Mission",
    "South Africa Johannesburg Mission",
    "South Africa Pretoria Mission",
    "South Korea Busan Mission",
    "South Korea Seoul Mission",
    "Spain Barcelona Mission",
    "Spain Madrid Mission",
    "Sri Lanka Colombo Mission",
    "Suriname Paramaribo Mission",
    "Swaziland Mbabane Mission",
    "Sweden Stockholm Mission",
    "Switzerland Zurich Mission",
    "Taiwan Taichung Mission",
    "Taiwan Taipei Mission",
    "Tanzania Dar es Salaam Mission",
    "Thailand Bangkok Mission",
    "Togo Lome Mission",
    "Tonga Nuku'alofa Mission",
    "Trinidad and Tobago Port of Spain Mission",
    "Tunisia Tunis Mission",
    "Turkey Istanbul Mission",
    "Uganda Kampala Mission",
    "Ukraine Dnipro Mission",
    "Ukraine Kyiv Mission",
    "United Arab Emirates Abu Dhabi Mission",
    "Uruguay Montevideo Mission",
    "Uruguay Montevideo West Mission",
    "Uruguay Rivera Mission",
    "Utah Layton Mission",
    "Utah Logan Mission",
    "Utah Ogden Mission",
    "Utah Orem Mission",
    "Utah Provo Mission",
    "Utah Salt Lake City Central Mission",
    "Utah Salt Lake City Mission",
    "Utah Salt Lake City South Mission",
    "Utah Salt Lake City West Mission",
    "Utah St. George Mission",
    "Utah Tooele Mission",
    "Utah West Valley City Mission",
    "Uzbekistan Tashkent Mission",
    "Vanuatu Port Vila Mission",
    "Venezuela Barcelona Mission",
    "Venezuela Caracas Mission",
    "Venezuela Maracaibo Mission",
    "Venezuela Maracay Mission",
    "Venezuela Merida Mission",
    "Venezuela Valencia Mission",
    "Vietnam Hanoi Mission",
    "Vietnam Ho Chi Minh City Mission",
    "Virginia Chesapeake Mission",
    "Virginia Richmond Mission",
    "Washington Everett Mission",
    "Washington Kennewick Mission",
    "Washington Seattle Mission",
    "Washington Spokane Mission",
    "Washington Tacoma Mission",
    "Washington Vancouver Mission",
    "West Indies Mission",
    "Zambia Lusaka Mission",
    "Zimbabwe Bulawayo Mission",
    "Zimbabwe Harare Mission"
]

st.title("I hope they call me on a mission!")
st.write("Enter your first and last name to receive your mission call!")

with st.form("mission_form"):
    first_name = st.text_input("First Name")
    last_name = st.text_input("Last Name")
    submitted = st.form_submit_button("Get My Mission Call!")

if submitted:
        if first_name.strip() and last_name.strip():
            mission_call = random.choice(missions)
            st.success(
                f"You are hereby called to serve as a missionary for the Church of Jesus Christ of Latter-day Saints. "
                f"You are assigned to labor in the **{mission_call}**."
            )
            # Show an image below the message
            st.image(
                "https://www.churchofjesuschrist.org/imgs/1f7c3e7d6e0b11edb1eecb7f3e4d5a2e4b6d9e7d/full/1600%2C/0/default",
                caption="Called to Serve!",
                use_column_width=True,
            )
        else:
            st.warning("Please enter both your first and last name.")
